import bcrypt from 'bcryptjs';

const data = {
  users: [
  ],
  products: [
    {
      name: 'Nature Plan Gatox mineral tablet for birds',
      slug: 'mineral tablet',
      animal: 'Bird',
      category: 'Bird-Food',
      image: 'https://sp-ao.shortpixel.ai/client/to_webp,q_glossy,ret_img,w_400/https://www.petsmall.pk/wp-content/uploads/2020/07/0012556_nature-plan-gatox-mineral-tablet-400x400.jpg',
      price: 250,
      countInStock: 5,
      brand: 'Nature Plan',
      rating: 4,
      numReviews: 0,
      description: 'minerals tablets',
  },
  {
      name: 'inter nutri-parrot food',
      slug: 'nutri-parrot',
      animal: 'Bird',
      category: 'Bird-Food',
      image: 'https://sp-ao.shortpixel.ai/client/to_webp,q_glossy,ret_img,w_300/https://www.petsmall.pk/wp-content/uploads/2020/11/Internutri_P%C3%A1te_beeding_3D-300x300.png',
      price: 750,
      countInStock: 10,
      brand: 'inter nutri',
      rating: 5,
      numReviews: 0,
      description: 'Food for Parrots',
  },
  {
      name: 'Vitakraft AFRICAN Food for African Small Parrots',
      slug: 'Vitakraft AFRICAN Food',
      animal: 'Bird',
      category: 'Bird-Food',
      image: 'https://sp-ao.shortpixel.ai/client/to_webp,q_glossy,ret_img,w_460/https://www.petsmall.pk/wp-content/uploads/2019/04/71ror3yktll._sy524_.jpg',
      price: 600,
      countInStock: 8,
      brand: 'Vitakraft',
      rating: 3,
      numReviews: 0,
      description: 'Small African Parrot seeds',
  },
  {
      name: 'Vitakraft CANARIAN for Canaries',
      slug: 'Vitakraft CANARIAN',
      animal: 'Bird',
      category: 'Bird-Food',
      image: 'https://sp-ao.shortpixel.ai/client/to_webp,q_glossy,ret_img,w_300/https://www.petsmall.pk/wp-content/uploads/2019/04/71e4wcuab9l._sy550_-300x300.jpg',
      price: 900,
      countInStock: 20,
      brand: 'Vitakraft',
      rating: 2.5,
      numReviews: 0,
      description: 'Seeds For Canaries',
  },
  {
      name: 'Vitakraft Food for Budgies',
      slug: 'Vitakraft Budgies',
      animal: 'Bird',
      category: 'Bird-Food',
      image: 'https://www.petsmall.pk/wp-content/uploads/2020/11/Internutri_P%C3%A1te_beeding_3D.png',
      price: 1000,
      countInStock: 10,
      brand: 'Vitakraft',
      rating: 3.5,
      numReviews: 0,
      description: 'Seeds For Budgies',
  },
  ],
};
export default data;
